### ISSUE TITLE
Fix test result titles

### ISSUE THREAD

**Issue by gregpabian** [benderjs/benderjs#225]
When a test case is nested in multiple test suites, only the name of the closest test's parent suite is shown on a test result list (while running a test file directly). This should be fixed and unified among all test frameworks.

**Comment by scofalik** [comment]
Either I do not understand what idea Grzegorz had or this is not a bug in bender core code. I am not exactly sure what Grzegorz meant by "unified among all test frameworks".

This bug is actually connected with bender- adapters, like bender-mocha, bender-YUI, etc. On results screen, bender displays what has been passed to it throught adapters, while adapters get their data from test frameworks. There is nothing we can do in Bender code. I will open appropriate issues in those repositories.

I am leaving this issue open until all our adapters are tweaked.

**Comment by scofalik** [comment]
AFAICS QUnit does not support nested modules.

**Comment by scofalik** [comment]
Jasmine tweaked with https://github.com/benderjs/benderjs-jasmine/commit/4bc983e0cece8252d53894a4d0f1f3953e7fbd70
