### ISSUE TITLE
Show error in console that someone tries to run dashboard from different host.

### ISSUE THREAD

**Issue by adelura** [benderjs/benderjs#231]
If we run bender using `bender server run` method, and then try to open dashboard from diffrent host - for example from virtual machine using local address then dashboard won't load.

It would be nice to show user that they have to setup `-H` flag, to allow access from diffrent hosts.

**Comment by Reinmar** [comment]
I don't think this is possible. You're not able to open Bender from a different host if Bender does not run on `0.0.0.0` because request from that host are not routed to Bender. So how could it notify you?

I think that we could change something else – the default host to `0.0.0.0`. Unfortunately, I'm not an expert in this and I know that it was confusing to Grzesiek too, so someone else would need to review this.
